#!/bin/zsh

set -e

function check_dependencies_or_die {
  (type jq &> /dev/null) || (echo "Cannot find 'jq' command, please install it first" && exit 1)
  (type curl &> /dev/null) || (echo "Cannot find 'curl' command, please install it first" && exit 1)
}

check_dependencies_or_die

./src/main
