#!/bin/zsh

function file_name {
  echo basename $0
}

function info {
  ([ "$LOG_LEVEL" = 'INFO' ] || [ "$LOG_LEVEL" = 'DEBUG' ]) && _log $1 'INFO' $2
}
function debug {
  [ "$LOG_LEVEL" = 'DEBUG' ] && _log $1 'DEBUG' $2
}
function error {
  [ "$LOG_LEVEL" != 'OFF' ] && _log $1 'ERROR' $2 >&2
}

# _log(lineNumber: Int, level: OFF | ERROR | INFO | DEBUG, msg: String)
function _log {
  echo "$(date -u "+%Y-%m-%dT%H:%M:%SZ" | tr -d '\n') $2\t$SCRIPT_NAME:$1\t$3"
}

# non_empty_or_exit(lineNumber: Int, value: String, key: String)
function non_empty_or_exit {
  debug $1 "non_empty_or_exit($1, $2, $3)"
  ([ "$2" = '' ] || [ "$2" = 'null' ]) && error "Invalid value for configuration key '$3': '$2' was empty" && exit 1
}
